version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/azurite"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      azurite:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/cassandra"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      cassandra:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/elasticsearch"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      elasticsearch:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/kafka"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      kafka:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/keycloak"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      keycloak:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/mailpit"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      mailpit:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/mongo"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      mongo:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/nats"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      nats:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/postgres"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      postgres:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/rabbitmq"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      rabbitmq:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/redis"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      redis:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/rustfs"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      rustfs:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/traefik"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      traefik:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/valkey"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      valkey:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "docker-compose"
    directory: "/wiremock"
    schedule:
      interval: "monthly"
    target-branch: main
    open-pull-requests-limit: 1
    groups:
      wiremock:
        patterns:
          - "*"
    labels:
      - "dependencies"
